docs: update nginx config adding breaking changes
coreruleset/modsecurity-docker pull request #115
Opened 2022-04-21 17:55 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Update documentation on beaking changes for nginx config.

2022-04-21 19:12 UTC, theseion requested changes
Good idea. Looks good, except for the misplaced (?) comment.

2022-04-21 19:12 UTC, theseion commented on README.md
> +    #  - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
This is in the wrong place, isn't it?

2022-04-21 22:29 UTC, fzipi360 commented on README.md
> +    #  - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
Definitely. Bad paste :)

2022-04-21 22:30 UTC, fzipi commented on README.md
> +    #  - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
Yes, bad paste.

2022-04-22 04:57 UTC, theseion requested changes
A typo and some wording changes.

2022-04-22 04:57 UTC, theseion commented on README.md
> +> 💬 What happens if I want to make changes in a different file, like `/etc/nging/conf.d/default.conf`?
```suggestion
> 💬 What happens if I want to make changes in a different file, like `/etc/nginx/conf.d/default.conf`?
```

2022-04-22 04:57 UTC, theseion commented on README.md
> +> You mount your local file, e.g. `nginx/default.conf` as the new template: `/etc/nginx/templates/conf.d/default.conf.template`. You can do the similar to other files. Files in the templates director
```suggestion
> You mount your local file, e.g. `nginx/default.conf` as the new template: `/etc/nginx/templates/conf.d/default.conf.template`. You can do this similarly with other files. Files in the templates directory will be copied and subdirectories will be preserved.
```

2022-04-22 05:12 UTC, theseion approved these changes

2022-04-22 16:28 UTC, merged